# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class TestSrvStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OneReqOneResp = channel.unary_unary(
                '/grpc_demo.TestSrv/OneReqOneResp',
                request_serializer=test__pb2.Req.SerializeToString,
                response_deserializer=test__pb2.MsgBatch.FromString,
                )
        self.MultiReqOneResp = channel.stream_unary(
                '/grpc_demo.TestSrv/MultiReqOneResp',
                request_serializer=test__pb2.Req.SerializeToString,
                response_deserializer=test__pb2.MsgBatch.FromString,
                )
        self.OneReqMultiResp = channel.unary_stream(
                '/grpc_demo.TestSrv/OneReqMultiResp',
                request_serializer=test__pb2.Req.SerializeToString,
                response_deserializer=test__pb2.MsgBatch.FromString,
                )
        self.MultiReqMultiResp = channel.stream_stream(
                '/grpc_demo.TestSrv/MultiReqMultiResp',
                request_serializer=test__pb2.Req.SerializeToString,
                response_deserializer=test__pb2.MsgBatch.FromString,
                )


class TestSrvServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OneReqOneResp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiReqOneResp(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OneReqMultiResp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiReqMultiResp(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestSrvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OneReqOneResp': grpc.unary_unary_rpc_method_handler(
                    servicer.OneReqOneResp,
                    request_deserializer=test__pb2.Req.FromString,
                    response_serializer=test__pb2.MsgBatch.SerializeToString,
            ),
            'MultiReqOneResp': grpc.stream_unary_rpc_method_handler(
                    servicer.MultiReqOneResp,
                    request_deserializer=test__pb2.Req.FromString,
                    response_serializer=test__pb2.MsgBatch.SerializeToString,
            ),
            'OneReqMultiResp': grpc.unary_stream_rpc_method_handler(
                    servicer.OneReqMultiResp,
                    request_deserializer=test__pb2.Req.FromString,
                    response_serializer=test__pb2.MsgBatch.SerializeToString,
            ),
            'MultiReqMultiResp': grpc.stream_stream_rpc_method_handler(
                    servicer.MultiReqMultiResp,
                    request_deserializer=test__pb2.Req.FromString,
                    response_serializer=test__pb2.MsgBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_demo.TestSrv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestSrv(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OneReqOneResp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_demo.TestSrv/OneReqOneResp',
            test__pb2.Req.SerializeToString,
            test__pb2.MsgBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MultiReqOneResp(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/grpc_demo.TestSrv/MultiReqOneResp',
            test__pb2.Req.SerializeToString,
            test__pb2.MsgBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OneReqMultiResp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc_demo.TestSrv/OneReqMultiResp',
            test__pb2.Req.SerializeToString,
            test__pb2.MsgBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MultiReqMultiResp(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/grpc_demo.TestSrv/MultiReqMultiResp',
            test__pb2.Req.SerializeToString,
            test__pb2.MsgBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
