# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\tgrpc_demo\"\"\n\x03Req\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\t\"3\n\x08MsgBatch\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\xf9\x01\n\x07TestSrv\x12\x36\n\rOneReqOneResp\x12\x0e.grpc_demo.Req\x1a\x13.grpc_demo.MsgBatch\"\x00\x12:\n\x0fMultiReqOneResp\x12\x0e.grpc_demo.Req\x1a\x13.grpc_demo.MsgBatch\"\x00(\x01\x12:\n\x0fOneReqMultiResp\x12\x0e.grpc_demo.Req\x1a\x13.grpc_demo.MsgBatch\"\x00\x30\x01\x12>\n\x11MultiReqMultiResp\x12\x0e.grpc_demo.Req\x1a\x13.grpc_demo.MsgBatch\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQ._serialized_start=25
  _REQ._serialized_end=59
  _MSGBATCH._serialized_start=61
  _MSGBATCH._serialized_end=112
  _TESTSRV._serialized_start=115
  _TESTSRV._serialized_end=364
# @@protoc_insertion_point(module_scope)
